### ISSUE TITLE
Helm install support

### ISSUE THREAD

**Issue by gluehbirnenkopf** [unbroken-dome/gradle-helm-plugin#1]
Hi,

I checked out your plugin, is it possible to execute "helm upgrade" or "helm install" or can I really only publish, manage and build charts?

**Comment by tkrullmann** [comment]
Hi! Yes, this is just not documented yet ;-)

Also please note this is all still work in progress, so it might still be buggy.

First, there's tasks for all of the common remote operations, so you can use the `HelmInstall` or `HelmUpgrade` task type directly. There's also a `HelmInstallOrUpgrade` task which does either `helm upgrade --install` or `helm install --replace` depending on a `replace` flag. All of these tasks are very similar in configuration though.

```groovy
task installOrUpgradeFoo(type: HelmInstallOrUpgrade) {
    chart = 'stable/mariadb'
    releaseName = 'mariadb'
    version = '5.1.1'
    values = [ 'rootUser.password': 'secret' ] // like --set command line flag
    valueFiles = files('mariadb.yaml')      // like -f command line flag
}
```

Alternatively (and preferred), there is also a separate plugin for this which builds on the base Helm plugin. It allows you to declare your releases using a DSL, and the tasks will be auto-generated. You can also reference charts that were built by other Helm tasks before.

```
plugins {
    id 'org.unbroken-dome.helm-releases' version '0.2.1'
}

helm {
    releases {
        mariadb {
            from 'stable/mariadb'
            version = '5.1.1'
            values = [ 'rootUser.password': 'secret' ] // like --set command line flag
            valueFiles = files('mariadb.yaml')      // like -f command line flag
        }
    }
}
```

This should automatically give you tasks `helmInstallMariadb` and `helmDeleteMariadb`.

For the target Kubernetes cluster you can configure most properties inside the `helm` or `helm.tiller` block. It is also possible to use project properties (they map pretty much directly e.g. `helm.kubeConfig`) so you can put these in your gradle.properties, or call it like this:

```./gradlew helmInstallMariadb -Phelm.kubeConfig=... -Phelm.kubeContext=...```

**Comment by gluehbirnenkopf** [comment]
Thanks for the quick reply! Will test all of this :)
