### ISSUE TITLE
Add support for publishing to Artifactory

### ISSUE THREAD

**Issue by lucimihai** [unbroken-dome/gradle-helm-plugin#10]
Helm publish task fails with error: org.apache.http.client.HttpResponseException: Method Not Allowed

Pls see some details from the log:

Executing request POST /artifactory/helm/api/charts HTTP/1.1
.....
Execution failed for task ':helmPublishMainChartToHelmArtifactoryRepo'.
[org.gradle.internal.buildevents.BuildExceptionReporter] > org.apache.http.client.HttpResponseException: Method Not Allowed

**Comment by vturime** [comment]
i am also facing the same issue. can anyone please look into it?

**Comment by tkrullmann** [comment]
Hi,

as the [documentation](https://unbroken-dome.github.io/projects/gradle-helm-plugin/#_publishing_charts) explains, there is currently no standard API for publishing Helm charts, so the plugin assumes [ChartMuseum](https://chartmuseum.com/) as it's one of the most widespread chart repos, and the first to define an HTTP API.

You can try and play around with the `uploadMethod` and `uploadPath` properties of the repository. I haven't used Artifactory as a Helm repo, but maybe setting the method to `PUT` is already enough (the default is `POST`). You will most likely also have to set the `uploadPath`, which is `/api/charts` by default (again, this is the ChartMuseum endpoint).

```groovy
helm.publishing.repositories {
    myRepo {
        uploadMethod = 'PUT'
        uploadPath = '...'
    }
}
```

**Comment by lucimihai** [comment]
It worked.

Thanks.
