### ISSUE TITLE
Cannot publish charts on Harbor registry

### ISSUE THREAD

**Issue by fmonorchio** [unbroken-dome/gradle-helm-plugin#100]
Hi all,

I want to upload charts in Harbor registry but when launch publish task it fails with this error:

`Chart repository server returned error response for POST /api/charts: 405 Method Not Allowed`

This is my gradle configuration:
```
helm {
    charts {
        main {
            chartName = "${project.name}-chart"
            sourceDir = file('src/k8s/resources')
        }
    }
    downloadClient {
        enabled = true
        version = "3.4.0"
    }
    publishing {
        repositories {
            chartMuseum('harbor') {
                url = uri('CHART_REPO')
                credentials {
                    username = 'USER'
                    password = 'PASSWORD'
                }
            }
        }
    }
}
```
I'm using plugin version 1.3.0

**Comment by tkrullmann** [comment]
Hi, and thanks for the report!

I did a bit of research and it seems that while Harbor uses Chartmuseum internally, it does so in [multi-tenancy](https://chartmuseum.com/docs/#multitenancy) mode, which this plugin unfortunately doesn't support yet.

Currently the plugin assumes that the URL path to upload a chart is `/api/charts`, this is pretty much hard-coded. However Harbor expects a URL path like `/api/chartrepo/<projectname>/charts`.

I will enhance the chartmuseum repository type so we can configure this in the Gradle DSL.

**Comment by tkrullmann** [comment]
Until it's implemented, you could try a `custom` repository with the following configuration as a workaround:

```groovy
publishing {
    repositories {
        custom('harbor') {
            url = 'https://your.harbor.server'
            uploadPath = '/api/chartrepo/<projectname>/charts'
            credentials { /* ... */ }
        }
    }
}
```

**Comment by abelsromero** [comment]
I am trying to publish to Harbor and none of the solutions here or in the docs seem to work.
The response is always a 404, tried with both the name and ID and no luck.

```
 POST https://{url}/api/chartrepo/{project-name or ID}/charts: 404 Not Found
```

Using cli `helm char push` works, so I don't think the publishing API is disabled...right?

**Comment by abelsromero** [comment]
I see in our instance the APIs available are
![image](https://user-images.githubusercontent.com/5781153/112132408-e1083c00-8bca-11eb-9fc8-a5c8a32ae9cf.png)

**Comment by kvmw** [comment]
> Until it's implemented, you could try a `custom` repository with the following configuration as a workaround:
> 
> ```groovy
> publishing {
>     repositories {
>         custom {
>             url = 'https://your.harbor.server'
>             uploadPath = '/api/chartrepo/<projectname>/charts'
>             credentials { /* ... */ }
>         }
>     }
> }
> ```

This solution is not working with our Harbor registry which uses API 2.0.

**Comment by asa-atallah** [comment]
Just wanted to note that publishing Harbor v2.5.4 seems to work fine with version 1.7.0 of the plugin, and that the normal `harbor` repository type can be used to accomplish it.  Note that this worked for me despite the fact that Harbor is exposing version 2.0 of its API (e.g. via Swagger).  The `custom` approach did not work however, as reported above.
