### ISSUE TITLE
init plugin failed in gradle

### ISSUE THREAD

**Issue by xiaoweialien** [unbroken-dome/gradle-helm-plugin#115]
build.gradle:

> plugins {
>     id("org.unbroken-dome.helm") version "1.6.0"
> }
> 
> helm {
>     charts {
>         oneems {
>             chartName = 'test'
>             chartVersion = '5.3.0'
>             sourceDir = file('src/main/helm')
>         }
>     }
> }

got error:
Build file 'D:\sandbox\helms\build.gradle' line: 2

An exception occurred applying plugin request [id: 'org.unbroken-dome.helm', version: '1.6.0']
> Failed to apply plugin [class 'org.unbrokendome.gradle.plugins.helm.command.HelmCommandsPlugin']
   > Could not create an instance of type org.unbrokendome.gradle.plugins.helm.dsl.DefaultHelmExtension.
      > Could not create an instance of type org.unbrokendome.gradle.plugins.helm.dsl.DefaultHelmDownloadClient.
         > 'void kotlin.jvm.internal.PropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'

**Comment by tkrullmann** [comment]
This was caused by a binary incompatibility between Kotlin 1.3 and 1.4 when using property references. It has been fixed in 1.6.1 (see #120)
