### ISSUE TITLE
Helm package does not read chartVersion

### ISSUE THREAD

**Issue by martinmosegaard** [unbroken-dome/gradle-helm-plugin#12]
It seems that the value `helm.charts.main.chartVersion` is not read or used by the `helmPackage` tasks. It only reads the version from `Chart.yaml`.

Perhaps because `helm package` is called without `--version` here: https://github.com/unbroken-dome/gradle-helm-plugin/blob/master/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmPackage.kt#L142

In my setup, it means that `helmPackage` creates a `tgz` with the version from `Chart.yaml` , but `helmPublish` then looks for an archive with the version specified by `project.version`.

Using plugin version 0.4.0.

**Comment by martinmosegaard** [comment]
Gradle code like this might be used as a workaround:

```
task copyHelmPackage(type: Copy) {
    from("${buildDir}/helm/charts/") {
        include "${project.name}-*.tgz"
    }
    into "${buildDir}/helm/charts/"
    rename '(.+)', "${project.name}-${project.version}.tgz"
}
copyHelmPackage.dependsOn(helmPackage)
helmPublish.dependsOn(copyHelmPackage)
```

let's say the chart version is `1.2.3` and project version is `4.5.6`, then:
- `helmPackage` creates `mychart-1.2.3.tgz`
- `copyHelmPackage` copies that to `mychart-4.5.6.tgz` in the same directory
- `helmPublish` finds `mychart-4.5.6.tgz`

**Comment by tkrullmann** [comment]
Hi,

thanks for the report! Totally makes sense. The `chartVersion` was mainly intended to be used as a replacement when filtering the Chart.yaml file:

```yaml
name: ${chartName}
version: ${chartVersion}
```

 I think it was required to have a `name` and `version` in the Chart.yaml anyway, with the Helm version that was current when I wrote the plugin. I'll check if this is still the case.
