### ISSUE TITLE
publish to ChartMuseum does not working

### ISSUE THREAD

**Issue by iamaverrick** [unbroken-dome/gradle-helm-plugin#15]
we came across your plugin and its an excellent plugin to work with i might say it solved a lot of repetitive tasks and automates the entire process.  with that being said we understand the plugin is fairly new and we are trying to incorporate in in our project we ran into a coupe of issue we need help with.
### project config

```
plugins {
	id 'war'
	id 'java'
	id 'idea'
	id 'groovy'
	id 'eclipse'
	id 'org.unbroken-dome.helm' version '0.4.0'
	id 'org.unbroken-dome.helm-publish' version '0.4.0'
	id 'org.unbroken-dome.helm-releases' version '0.4.0'
	id 'org.unbroken-dome.helm-commands' version '0.4.0'
}

helm {
	home = file("${project.buildDir}/helm/home")

	filtering {
		// This value will be resolvable in all charts' YAML files as "${springProfile}"
		values.put 'springProfile', 'prod'
	}

	charts {
		web {
			chartName = "${project.name}"
			chartVersion = "${project.version}"
			sourceDir = file('src/main/charts/web')
		}
	}

	repositories {
		company {
			url = uri('https://chartmuseum.example.com/')
			credentials {
				username = 'USERNAME'
				password = 'PASSWORD'
			}
		}
	}

	publishing {
		repositories {
			chartMuseum('company') {
				url = uri('https://chartmuseum.example.com/')
				credentials {
					username = 'USERNAME'
					password = 'PASSWORD'
				}
			}
		}
	}

	releases {
		web {
//			from "company/${project.name}"
//			version = "${project.version}"
			from "charts/${project.name}"

		}
	}
}
```

### Repo Production Environment 
we currently are running the repo in a private network which can be access via vpn, and we use SSL 

### Error message
Error: Looks like "https://chartmuseum.example.com/" is not a valid chart repository or cannot be reached: Get https://chartmuseum.example.com/index.yaml: dial tcp 10.10.3.210:443: connect: operation timed out

### Testing

when testing to see if i'm able to push charts to the repo or pull we use the following command 

`
helm repo add company https://chartmuseum.example.com --username USERNAME --password 'PASSWORD'

`

and everything works perfect so i know their isn't any issues with the actual repo running in a private network and ssl

would you be able to guide me on what seems to be the issue at hand thanks in advance

**Comment by tkrullmann** [comment]
Hi,

I don't think this is related to publishing at all. The error message you posted is from `helm repo add`, it's not logged by the plugin. The plugin task really just calls `helm repo add` with the supplied parameters, so the only differences that I could think of:

- The URL in your command line example doesn't end with a forward slash `/` but the one in your Gradle script does. Still, I'd be surprised if Helm treats these differently.
- Depending on how your VPN and SSL certificates are set up, the `helm` process spawned by the plugin could have a different environment, e.g. environment variables. It will inherit the environment from the Gradle (daemon) process that forks it. To check if there are any differences, you could add some code to your scripts that prints all the environment variables, and then compare that with what `env` gives you on the shell.

**Comment by iamaverrick** [comment]
Hello,

we have isolated the problem to be with the VPN, we noticed that while running the OpenVPN client the script worked, and while turned off it wouldn't work. so we have a solution to resolve this issue and thats by moving the ChartMuseum out of private VPC which will ultimately resolve this issue. unless you can specify a solution to work through the private network?

**Comment by iamaverrick** [comment]
resolved issue by moving url to public aws vpc
