### ISSUE TITLE
Allow specifying `--create-namespace` on a helm install command

### ISSUE THREAD

**Issue by NikolayMetchev** [unbroken-dome/gradle-helm-plugin#156]
Hello
It would be useful to be able to pass the --create-namespace command to helm install.
Please add support for it.
Many thanks

**Comment by NikolayMetchev** [comment]
oops. seems like that is possible. I couldn't find it in the docs.

**Comment by NikolayMetchev** [comment]
I tried this but it doesn't seem to apply the option
```
tasks.withType<AbstractHelmInstallationCommandTask> {
    createNamespace.set(true)
}
```

**Comment by KarlHakanNordgren** [comment]
@NikolayMetchev : It's possible by specifying `helm.releases.<releaseName>.createNamespace = true`.
