### ISSUE TITLE
A possibility to configure 'channel' at Gitlab Helm Repositories

### ISSUE THREAD

**Issue by mehmetsalgar** [unbroken-dome/gradle-helm-plugin#163]
This is actually a feature request...

Gitlab Helm Repository has a possibility to  configure [channels](https://docs.gitlab.com/ee/user/packages/helm_repository/#release-channels).

As far as I can see at the moment it is not possible to configure 'channel' at gradle plugin.

[upload-path](https://github.com/unbroken-dome/gradle-helm-plugin/blob/2d5b9b1feec43d5b1429d97ba013281ffa574b0b/helm-publish-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/dsl/GitlabHelmPublishingRepository.kt#L63-L65)

I think, it is not a huge problem to place a 'channel' property that will replace 'stable'..

I am not quite sure from Gitlab documentation which values are possible, 'stable' and 'devel' are definitively there but may be as free text also (I like to simulate here 'feature-branches' so all publish are not going directly to stable)

**Comment by tkrullmann** [comment]
part of release 2.0.0
