### ISSUE TITLE
HelmInit seems to ignore the `wait` property

### ISSUE THREAD

**Issue by sam-sla** [unbroken-dome/gradle-helm-plugin#17]
I am configuring the init task as:

```
task helmInit(type: HelmInit) {
    dependsOn helmAddRepository

    replicas = 1 // Amount of Tiller instances to run on the cluster.
    skipRefresh = false
    upgrade = true
    wait = true
    debug = true
}
```

but in gradle's output I can see that the `--wait` flag is not being passed:
`Executing: [helm, init, --debug, --replicas, 1]`

**Workaround:**

I think I can use `extraArgs` for now and pass `--wait` directly to helm.

**Comment by tkrullmann** [comment]
It should be fixed in version 0.4.1, please try
