### ISSUE TITLE
Maintenance plans for gradle-helm-plugin

### ISSUE THREAD

**Issue by JamieSlome** [unbroken-dome/gradle-helm-plugin#177]
Hello @tkrullmann 👋 

I'd like to understand whether this project will continue to be actively maintained moving forward.

This isn't in the form of any expectation on you, but more so we can best plan whether to submit contributions to this project or move forward with a fork. I saw [v2.0.0](https://github.com/unbroken-dome/gradle-helm-plugin/releases/tag/v2.0.0) published 3 weeks ago, but prior to this, commit activity was around 1-1.5 years ago?

We have various bug fixes and features that we would love to contribute and also want to extend our support, if welcome, to support you on this project if you don't have the time to maintain and respond to community requests.

Most importantly, thank you for all the work you have done on the project to date! 🤝

**Comment by JamieSlome** [comment]
@tkrullmann - thanks for the response, and understood clearly!

1. Would you be happy to redirect contributors to [our fork](https://github.com/Citi/gradle-helm-plugin)?
2. Would you archive this repository or simply endorse all future contributions to our fork?

From Gradle's perspective, they won't allow the publication of a plugin if it is a fork, so we'd just need to make it clear to the Gradle Support team, that the new fork is preferred by you?

The fork approach seems better here as there is a little more involved with gaining access to the repository, transferring it, and publishing the plugin under the same Gradle Plugins namespace - thoughts?

**Comment by tkrullmann** [comment]
I added a closure/redirect notice. Thanks for taking over, and good luck!

**Comment by JamieSlome** [comment]
Thanks, @tkrullmann 👍
