### ISSUE TITLE
helm 3.0 support

### ISSUE THREAD

**Issue by Blobson** [unbroken-dome/gradle-helm-plugin#23]
For now it fails with an error: `Error: unknown flag: --client-only`

**Comment by Emilio-Pega** [comment]
PR for helm 3 support: https://github.com/unbroken-dome/gradle-helm-plugin/pull/25

**Comment by tmeltser** [comment]
Any update on when this ability will be published?

**Comment by tkrullmann** [comment]
Finally got the chance for this, plugin should be fully Helm3 compatible now.
