### ISSUE TITLE
Possibility to disable dependency update tasks

### ISSUE THREAD

**Issue by Blobson** [unbroken-dome/gradle-helm-plugin#24]
Sometimes it is useful to skip dependency update task if requirements.yaml contains dependencies to only local subcharts. Due to the following helm issue it is not possible right now: https://github.com/helm/helm/issues/3742
It would be nice if you could disable dependency update for a specific chart. Here is an example:
```
helm {
    charts {
        foo {
            chartName = 'foo'
            chartVersion = '1.2.3'
            sourceDir = file('src/helm')
            skipDependencyUpdate = true
        }
    }
}
```

**Comment by tkrullmann** [comment]
The `HelmUpdateDependencies` task now has a smart check that inspects the _Chart.yaml_ / _requirements.yaml_ and reports SKIPPED (without calling `helm dep up`) if there are only local dependencies.
("Local" dependencies as in, they don't have a `repository` property)
