### ISSUE TITLE
Cannot create a HelmTest task

### ISSUE THREAD

**Issue by GianniGiglio** [unbroken-dome/gradle-helm-plugin#26]
Question: I can't seem to create a HelmTest task
Could not create task of type 'HelmTest'.
      > Class org.unbrokendome.gradle.plugins.helm.command.tasks.HelmTest is final.

Is there a way to create a HelmTest task?

Thanks

**Comment by tkrullmann** [comment]
HelmTest task class wasn't declared as `open`, this is required by Gradle so it can decorate the task.
