### ISSUE TITLE
With helm3: timeoutSeconds property takes only integer but --timeout flag needs integer and timeunit

### ISSUE THREAD

**Issue by sskrishnav** [unbroken-dome/gradle-helm-plugin#29]
The **timeoutSeconds**  property accepts integer.
Eg: `timeoutSeconds = 1000`
Eventually, this property will convert into **--timeout** flag for the actual command.
Eg: `helm xxxxxxxxxxxxxxxxxxxxxxxx --timeout 1000`

The actual **--timeout** flag excepts an integer with time unit(s or m), So we are encountering an error.
Eg: `--timeout 1000s `or `--timeout 1000m`

`Error: invalid argument "1000" for "--timeout" flag: time: missing unit in duration 1000`

**Comment by tkrullmann** [comment]
This has been addressed in the 1.0 version and Helm3 compatibility. Timeout (which is called `remoteTimeout` now) can take various forms:

- plain integer (interpreted as seconds)
- Helm-syntax duration (e.g. `3m30s`)
- ISO syntax duration (e.g. `PT3M30S`)
- `java.time.Duration` (when setting programmatically in the buildscript)

all of them will be converted to a Helm3-compatible duration string for the CLI call.
