### ISSUE TITLE
HelmLint task fails with 'Transformer for this provider returned a null value'

### ISSUE THREAD

**Issue by marcoferrer** [unbroken-dome/gradle-helm-plugin#35]
Helm lint tasks fail exceptionally in a fresh project with the following error message: `Transformer for this provider returned a null value`

Digging through the source it looks like the following snippet is the culprit. 

https://github.com/unbroken-dome/gradle-helm-plugin/blob/ba0af70ee1e3b07dfc6c175497f18998bb1c62b1/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmValueOptions.kt#L109-L126

Specifically `options.fileValues.map<String> {` resolves to `AbstractMinimalProvider.map` at runtime and not the kotlin stdlib map. 
Turns out that the lambda used for mapping is not allowed to return null which can occur at `m.takeIf { it.isNotEmpty() } `

**Comment by tkrullmann** [comment]
I just noticed that as well. Thanks for the fix!
