### ISSUE TITLE
HelmExec not masked

### ISSUE THREAD

**Issue by quarkie** [unbroken-dome/gradle-helm-plugin#40]
running tasks that do a helmExec internally  e.g helmAddMyRepository -i
produces the following output:
`> Task :helmAddMyRepository
Caching disabled for task ':helmAddMyRepository' because:
  Build cache is disabled
Task ':helmAddMyRepository' is not up-to-date because:
  Task.upToDateWhen is false.
Executing: [helm, repo, add, --username, myUser, --password, ******, my, https://localhost/artifactory/helm3]
Starting process 'command 'helm''. Working directory: C:\myChart Command: helm repo add --username myUser --password myPassword my https://localhost/artifactory/helm3`

The helmExec should be masked as well. Currently passwords are printed in cleartext

**Comment by tkrullmann** [comment]
I'm not sure if that will be possible. As you see there is one log line from the plugin itself (where the password is properly masked), the other one is from Gradle logging the `exec` call. I will check if there's a way to mask certain parameters there, but I haven't seen anything like that in the Gradle API.

**Comment by quarkie** [comment]
I might also have an Look at it. I Just wanted to Adress this behaviour. Maybe it is something to address to gradle.
