### ISSUE TITLE
Ability to check release status

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [unbroken-dome/gradle-helm-plugin#41]
It would be great if `helm-releases` plugin would have possibility to check release status.

Task `helmStatus<X>` could be added, which checks status of release named X by calling `helm status`.

**Comment by tkrullmann** [comment]
Thanks for the suggestion!
What would you suggest as the output of such a task? Simply reporting the status on the console?

**Comment by PrzemyslawSwiderski** [comment]
Output can can look like a normal output of executing `helm status` command.
I guess simple `table` output format would be satisfactory but if there could be possibility to specify other formats such as `json` or `yam` it would be great.
