### ISSUE TITLE
Create namespace flag support

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [unbroken-dome/gradle-helm-plugin#43]
With helm 3.2.0 version, it is now possible to create namespace by specifying `--create-namespace` flag in `helm install` or `upgrade --install` command.

Are there any plans to add this flag support? 
Maybe possibility to add custom args when releasing (like `helm.extraArgs` property) would be enough?

**Comment by tkrullmann** [comment]
Yes, I'm planning to support all command-line flags (at least the ones that make sense in an automated build) as properties in the plugin. Thanks for the heads-up!
Supporting an `extraArgs` specifically for releases is also a good idea.

**Comment by tkrullmann** [comment]
implemented with PR #49, will be in next release
