### ISSUE TITLE
[ERROR] Chart.yaml: version should be of type string but it's of type float64

### ISSUE THREAD

**Issue by tonsV2** [unbroken-dome/gradle-helm-plugin#64]
I'm getting the following error while trying to execute `./gradlew helmPackage`.

```
> Task :helmLintMainChart FAILED
cmd_run.go:918: WARNING: cannot create user data directory: failed to verify SELinux context of /home/tons/snap: exec: "matchpathcon": executable file not found in $PATH
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting /home/tons/IdeaProjects/whoami-mn/build/helm/charts/whoami
[ERROR] Chart.yaml: version should be of type string but it's of type float64
[INFO] Chart.yaml: icon is recommended


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':helmLintMainChart'.
> A failure occurred while executing org.unbrokendome.gradle.plugins.helm.command.HelmExecWorkAction
   > Process 'command 'helm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
4 actionable tasks: 1 executed, 3 up-to-date
```

The command `helm package src/main/helm/` works just fine though.

Any clue what's going wrong? Please let me know if I should post parts of my chart or setup

**Comment by tonsV2** [comment]
The reason why I didn't post my Chart.yaml is because it makes no difference whether I quote my version property or not. Any this plugin works just fine for one project but in the other I get the error I posted above and I can't find a solution.

**Comment by tkrullmann** [comment]
Hi,

is your version SemVer compatible? Helm trying to interpret it as a float sounds like it might be something like `1.2`

**Comment by tkrullmann** [comment]
Also, the plugin will call `helm package` with the `--version` option. It passes the version that is configured in the `chartVersion` property for the chart, which defaults to the Gradle project version if not set. So if your Gradle project version is not Semver compatible, you might have to set the chart version explicitly to something else:

```
helm {
    charts {
        register("foo") {
            chartVersion.set("1.2.3")
        }
    }
}
```

Btw apparently `helm package --version` doesn't quote the version when it injects it into the Chart.yaml, that's why your quoting the version doesn't help

**Comment by tkrullmann** [comment]
If you run Gradle with the `--info` flag, you will see exactly what invocations of `helm` CLI are being made.

**Comment by tonsV2** [comment]
The problem was solved by defining the application version in gradle with three digits rather than just two. Thanks for the support!
