### ISSUE TITLE
downloadClient: Cannot cast object 'true' with class 'Boolean' to class 'Property'

### ISSUE THREAD

**Issue by wingsofovnia** [unbroken-dome/gradle-helm-plugin#73]
I am trying to enable client downloading as per [docs](https://unbroken-dome.github.io/projects/gradle-helm-plugin/#_automatic_download_of_the_helm_client):
```groovy
// build.gradle
helm {
    downloadClient {
        enabled = true
        version = '3.2.0'
    }
}
```
However, this is what I get on Gradle 6.6:
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'org.gradle.api.provider.Property'
```
However, Kotlin syntax works:
```groovy
helm {
    downloadClient {
        enabled.set(true)
        version.set("3.2.0")
    }
}
```

It is strange because it seems other closures don't have this problem:
```groovy
helm {
    downloadClient {
        enabled.set(true)
        version.set("3.2.0")
    }
    // works as expected
    lint {
        strict = true
    }
}
```

**Comment by tkrullmann** [comment]
Interesting. One difference is that many of the other blocks are instantiated by `ObjectFactory.newInstance`, while the `downloadClient` is just a POJO owned by the HelmExtension directly. I always thought the Groovy syntactic sugar for setting properties was something that Gradle makes generally available, not just for objects instantiated via `ObjectFactory`. Will investigate!
