### ISSUE TITLE
Support for native helm publishing

### ISSUE THREAD

**Issue by erikmartino** [unbroken-dome/gradle-helm-plugin#84]
Not all helm repos are http(s) based, a good example is the s3 helm plugin. It would be nice to have a publishing plugin that uses the the `helm` command to publish to leverage helm repository plugins.

**Comment by tkrullmann** [comment]
As far as I know, there are no officially endorsed plugins for Helm - only those contributed by the community. Also, there doesn't seem to be a single Helm plugin that can handle different sorts of chart repository types (S3, GCS etc.) - each of those requires a different Helm plugin.

That means, for the Gradle plugin to support any of these publishing mechanisms, it would have to work with a specific Helm plugin and its syntax, include a check that the plugin is installed, or install it on-demand if the `downloadClient` feature is enabled. This would probably be a lot more work than just implementing a separate publishing repository type for those targets directly in the Gradle plugin.

I'll put support for S3 and GCS chart repositories on the roadmap. If one day a generic publishing support finally gets built into the Helm client itself, I will happily make that available in the Gradle plugin.
